# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: algorithm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='algorithm.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x61lgorithm.proto\"\'\n\x03Two\x12\x0f\n\x07number1\x18\x01 \x01(\x05\x12\x0f\n\x07number2\x18\x02 \x01(\x05\"\x16\n\x03One\x12\x0f\n\x07number1\x18\x01 \x01(\x05\x32 \n\tAlgorithm\x12\x13\n\x03\x41\x64\x64\x12\x04.Two\x1a\x04.One\"\x00\x62\x06proto3'
)




_TWO = _descriptor.Descriptor(
  name='Two',
  full_name='Two',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number1', full_name='Two.number1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='number2', full_name='Two.number2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=58,
)


_ONE = _descriptor.Descriptor(
  name='One',
  full_name='One',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number1', full_name='One.number1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['Two'] = _TWO
DESCRIPTOR.message_types_by_name['One'] = _ONE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Two = _reflection.GeneratedProtocolMessageType('Two', (_message.Message,), {
  'DESCRIPTOR' : _TWO,
  '__module__' : 'algorithm_pb2'
  # @@protoc_insertion_point(class_scope:Two)
  })
_sym_db.RegisterMessage(Two)

One = _reflection.GeneratedProtocolMessageType('One', (_message.Message,), {
  'DESCRIPTOR' : _ONE,
  '__module__' : 'algorithm_pb2'
  # @@protoc_insertion_point(class_scope:One)
  })
_sym_db.RegisterMessage(One)



_ALGORITHM = _descriptor.ServiceDescriptor(
  name='Algorithm',
  full_name='Algorithm',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=84,
  serialized_end=116,
  methods=[
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='Algorithm.Add',
    index=0,
    containing_service=None,
    input_type=_TWO,
    output_type=_ONE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ALGORITHM)

DESCRIPTOR.services_by_name['Algorithm'] = _ALGORITHM

# @@protoc_insertion_point(module_scope)
